stages:
  - unit-tests

# before_script:
#   - gem install bundler
#   - bundle install
#   - pod install

unit_tests:
  dependencies: []
  stage: unit-tests
  artifacts:
    paths:
      - fastlane/screenshots
      - fastlane/logs
  script:
    - fastlane tests