stages:
  - unit-tests

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

unit_tests:
  dependencies: []
  stage: unit-tests
  artifacts:
    paths:
      - fastlane/screenshots
      - fastlane/logs
  script:
    - bundle exec fastlane tests