default_platform(:ios)

platform :ios do
  desc "Run all unit-tests"
  lane :tests do
    run_tests(workspace: "Minipomo.xcworkspace",
              devices: ["iPhone 11"],
              scheme: "Minipomo")
  end

  desc "Run SwiftLint"
  lane :lint do
    swiftlint(
      mode: :lint,
      strict: true,
      output_file: "swiftlint.result.json",
      config_file: ".swiftlint.yml",
      raise_if_swiftlint_error: true,
      ignore_exit_status: true
    )
end
