default_platform(:ios)

platform :ios do
  desc "Run all unit-tests"
  lane :tests do
    run_tests(workspace: "Minipomo.xcworkspace",
              devices: ["iPhone 11"],
              scheme: "Minipomo")
  end
end
